name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ClocViewer-${{github.sha}}
        path: ./src/ClocViewer/bin/Debug/net5.0-windows/publish
        retention-days: 90
